/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppPricePointV2RelationshipsPriceTier } from './AppPricePointV2RelationshipsPriceTier';
import {
    AppPricePointV2RelationshipsPriceTierFromJSON,
    AppPricePointV2RelationshipsPriceTierFromJSONTyped,
    AppPricePointV2RelationshipsPriceTierToJSON,
} from './AppPricePointV2RelationshipsPriceTier';
import type { AppPricePointV2RelationshipsTerritory } from './AppPricePointV2RelationshipsTerritory';
import {
    AppPricePointV2RelationshipsTerritoryFromJSON,
    AppPricePointV2RelationshipsTerritoryFromJSONTyped,
    AppPricePointV2RelationshipsTerritoryToJSON,
} from './AppPricePointV2RelationshipsTerritory';

/**
 * 
 * @export
 * @interface AppPricePointRelationships
 */
export interface AppPricePointRelationships {
    /**
     * 
     * @type {AppPricePointV2RelationshipsPriceTier}
     * @memberof AppPricePointRelationships
     */
    priceTier?: AppPricePointV2RelationshipsPriceTier;
    /**
     * 
     * @type {AppPricePointV2RelationshipsTerritory}
     * @memberof AppPricePointRelationships
     */
    territory?: AppPricePointV2RelationshipsTerritory;
}

/**
 * Check if a given object implements the AppPricePointRelationships interface.
 */
export function instanceOfAppPricePointRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppPricePointRelationshipsFromJSON(json: any): AppPricePointRelationships {
    return AppPricePointRelationshipsFromJSONTyped(json, false);
}

export function AppPricePointRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPricePointRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceTier': !exists(json, 'priceTier') ? undefined : AppPricePointV2RelationshipsPriceTierFromJSON(json['priceTier']),
        'territory': !exists(json, 'territory') ? undefined : AppPricePointV2RelationshipsTerritoryFromJSON(json['territory']),
    };
}

export function AppPricePointRelationshipsToJSON(value?: AppPricePointRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceTier': AppPricePointV2RelationshipsPriceTierToJSON(value.priceTier),
        'territory': AppPricePointV2RelationshipsTerritoryToJSON(value.territory),
    };
}

