/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppPriceTierRelationshipsPricePointsDataInner
 */
export interface AppPriceTierRelationshipsPricePointsDataInner {
    /**
     * 
     * @type {string}
     * @memberof AppPriceTierRelationshipsPricePointsDataInner
     */
    type: AppPriceTierRelationshipsPricePointsDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppPriceTierRelationshipsPricePointsDataInner
     */
    id: string;
}


/**
 * @export
 */
export const AppPriceTierRelationshipsPricePointsDataInnerTypeEnum = {
    AppPricePoints: 'appPricePoints'
} as const;
export type AppPriceTierRelationshipsPricePointsDataInnerTypeEnum = typeof AppPriceTierRelationshipsPricePointsDataInnerTypeEnum[keyof typeof AppPriceTierRelationshipsPricePointsDataInnerTypeEnum];


/**
 * Check if a given object implements the AppPriceTierRelationshipsPricePointsDataInner interface.
 */
export function instanceOfAppPriceTierRelationshipsPricePointsDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AppPriceTierRelationshipsPricePointsDataInnerFromJSON(json: any): AppPriceTierRelationshipsPricePointsDataInner {
    return AppPriceTierRelationshipsPricePointsDataInnerFromJSONTyped(json, false);
}

export function AppPriceTierRelationshipsPricePointsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPriceTierRelationshipsPricePointsDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AppPriceTierRelationshipsPricePointsDataInnerToJSON(value?: AppPriceTierRelationshipsPricePointsDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

