/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppStoreVersionExperimentTreatment } from './AppStoreVersionExperimentTreatment';
import {
    AppStoreVersionExperimentTreatmentFromJSON,
    AppStoreVersionExperimentTreatmentFromJSONTyped,
    AppStoreVersionExperimentTreatmentToJSON,
} from './AppStoreVersionExperimentTreatment';
import type { AppStoreVersionExperimentTreatmentsResponseIncludedInner } from './AppStoreVersionExperimentTreatmentsResponseIncludedInner';
import {
    AppStoreVersionExperimentTreatmentsResponseIncludedInnerFromJSON,
    AppStoreVersionExperimentTreatmentsResponseIncludedInnerFromJSONTyped,
    AppStoreVersionExperimentTreatmentsResponseIncludedInnerToJSON,
} from './AppStoreVersionExperimentTreatmentsResponseIncludedInner';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface AppStoreVersionExperimentTreatmentResponse
 */
export interface AppStoreVersionExperimentTreatmentResponse {
    /**
     * 
     * @type {AppStoreVersionExperimentTreatment}
     * @memberof AppStoreVersionExperimentTreatmentResponse
     */
    data: AppStoreVersionExperimentTreatment;
    /**
     * 
     * @type {Array<AppStoreVersionExperimentTreatmentsResponseIncludedInner>}
     * @memberof AppStoreVersionExperimentTreatmentResponse
     */
    included?: Array<AppStoreVersionExperimentTreatmentsResponseIncludedInner>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof AppStoreVersionExperimentTreatmentResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the AppStoreVersionExperimentTreatmentResponse interface.
 */
export function instanceOfAppStoreVersionExperimentTreatmentResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function AppStoreVersionExperimentTreatmentResponseFromJSON(json: any): AppStoreVersionExperimentTreatmentResponse {
    return AppStoreVersionExperimentTreatmentResponseFromJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionExperimentTreatmentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AppStoreVersionExperimentTreatmentFromJSON(json['data']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(AppStoreVersionExperimentTreatmentsResponseIncludedInnerFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function AppStoreVersionExperimentTreatmentResponseToJSON(value?: AppStoreVersionExperimentTreatmentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppStoreVersionExperimentTreatmentToJSON(value.data),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(AppStoreVersionExperimentTreatmentsResponseIncludedInnerToJSON)),
        'links': DocumentLinksToJSON(value.links),
    };
}

