/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppUpdateRequestDataRelationshipsAvailableTerritories } from './AppUpdateRequestDataRelationshipsAvailableTerritories';
import {
    AppUpdateRequestDataRelationshipsAvailableTerritoriesFromJSON,
    AppUpdateRequestDataRelationshipsAvailableTerritoriesFromJSONTyped,
    AppUpdateRequestDataRelationshipsAvailableTerritoriesToJSON,
} from './AppUpdateRequestDataRelationshipsAvailableTerritories';
import type { AppUpdateRequestDataRelationshipsPrices } from './AppUpdateRequestDataRelationshipsPrices';
import {
    AppUpdateRequestDataRelationshipsPricesFromJSON,
    AppUpdateRequestDataRelationshipsPricesFromJSONTyped,
    AppUpdateRequestDataRelationshipsPricesToJSON,
} from './AppUpdateRequestDataRelationshipsPrices';

/**
 * 
 * @export
 * @interface AppUpdateRequestDataRelationships
 */
export interface AppUpdateRequestDataRelationships {
    /**
     * 
     * @type {AppUpdateRequestDataRelationshipsPrices}
     * @memberof AppUpdateRequestDataRelationships
     */
    prices?: AppUpdateRequestDataRelationshipsPrices;
    /**
     * 
     * @type {AppUpdateRequestDataRelationshipsAvailableTerritories}
     * @memberof AppUpdateRequestDataRelationships
     */
    availableTerritories?: AppUpdateRequestDataRelationshipsAvailableTerritories;
}

/**
 * Check if a given object implements the AppUpdateRequestDataRelationships interface.
 */
export function instanceOfAppUpdateRequestDataRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppUpdateRequestDataRelationshipsFromJSON(json: any): AppUpdateRequestDataRelationships {
    return AppUpdateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function AppUpdateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUpdateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prices': !exists(json, 'prices') ? undefined : AppUpdateRequestDataRelationshipsPricesFromJSON(json['prices']),
        'availableTerritories': !exists(json, 'availableTerritories') ? undefined : AppUpdateRequestDataRelationshipsAvailableTerritoriesFromJSON(json['availableTerritories']),
    };
}

export function AppUpdateRequestDataRelationshipsToJSON(value?: AppUpdateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prices': AppUpdateRequestDataRelationshipsPricesToJSON(value.prices),
        'availableTerritories': AppUpdateRequestDataRelationshipsAvailableTerritoriesToJSON(value.availableTerritories),
    };
}

