/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface DiagnosticLog
 */
export interface DiagnosticLog {
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLog
     */
    type: DiagnosticLogTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticLog
     */
    id: string;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof DiagnosticLog
     */
    links: ResourceLinks;
}


/**
 * @export
 */
export const DiagnosticLogTypeEnum = {
    DiagnosticLogs: 'diagnosticLogs'
} as const;
export type DiagnosticLogTypeEnum = typeof DiagnosticLogTypeEnum[keyof typeof DiagnosticLogTypeEnum];


/**
 * Check if a given object implements the DiagnosticLog interface.
 */
export function instanceOfDiagnosticLog(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function DiagnosticLogFromJSON(json: any): DiagnosticLog {
    return DiagnosticLogFromJSONTyped(json, false);
}

export function DiagnosticLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'links': ResourceLinksFromJSON(json['links']),
    };
}

export function DiagnosticLogToJSON(value?: DiagnosticLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'links': ResourceLinksToJSON(value.links),
    };
}

