/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlternativeDistributionPackageDeltaResponse,
  ErrorResponse,
} from '../models';
import {
    AlternativeDistributionPackageDeltaResponseFromJSON,
    AlternativeDistributionPackageDeltaResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models';

export interface AlternativeDistributionPackageDeltasGetInstanceRequest {
    id: string;
    fieldsAlternativeDistributionPackageDeltas?: Array<AlternativeDistributionPackageDeltasGetInstanceFieldsAlternativeDistributionPackageDeltasEnum>;
}

/**
 * 
 */
export class AlternativeDistributionPackageDeltasApi extends runtime.BaseAPI {

    /**
     */
    async alternativeDistributionPackageDeltasGetInstanceRaw(requestParameters: AlternativeDistributionPackageDeltasGetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlternativeDistributionPackageDeltaResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling alternativeDistributionPackageDeltasGetInstance.');
        }

        const queryParameters: any = {};

        if (requestParameters.fieldsAlternativeDistributionPackageDeltas) {
            queryParameters['fields[alternativeDistributionPackageDeltas]'] = requestParameters.fieldsAlternativeDistributionPackageDeltas.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itc-bearer-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/alternativeDistributionPackageDeltas/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlternativeDistributionPackageDeltaResponseFromJSON(jsonValue));
    }

    /**
     */
    async alternativeDistributionPackageDeltasGetInstance(requestParameters: AlternativeDistributionPackageDeltasGetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlternativeDistributionPackageDeltaResponse> {
        const response = await this.alternativeDistributionPackageDeltasGetInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AlternativeDistributionPackageDeltasGetInstanceFieldsAlternativeDistributionPackageDeltasEnum = {
    AlternativeDistributionKeyBlob: 'alternativeDistributionKeyBlob',
    FileChecksum: 'fileChecksum',
    Url: 'url',
    UrlExpirationDate: 'urlExpirationDate'
} as const;
export type AlternativeDistributionPackageDeltasGetInstanceFieldsAlternativeDistributionPackageDeltasEnum = typeof AlternativeDistributionPackageDeltasGetInstanceFieldsAlternativeDistributionPackageDeltasEnum[keyof typeof AlternativeDistributionPackageDeltasGetInstanceFieldsAlternativeDistributionPackageDeltasEnum];
