/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlternativeDistributionPackageVersionRelationshipsDeltasDataInner
 */
export interface AlternativeDistributionPackageVersionRelationshipsDeltasDataInner {
    /**
     * 
     * @type {string}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltasDataInner
     */
    type: AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltasDataInner
     */
    id: string;
}


/**
 * @export
 */
export const AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerTypeEnum = {
    AlternativeDistributionPackageDeltas: 'alternativeDistributionPackageDeltas'
} as const;
export type AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerTypeEnum = typeof AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerTypeEnum[keyof typeof AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerTypeEnum];


/**
 * Check if a given object implements the AlternativeDistributionPackageVersionRelationshipsDeltasDataInner interface.
 */
export function instanceOfAlternativeDistributionPackageVersionRelationshipsDeltasDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSON(json: any): AlternativeDistributionPackageVersionRelationshipsDeltasDataInner {
    return AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSONTyped(json, false);
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeDistributionPackageVersionRelationshipsDeltasDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSON(value?: AlternativeDistributionPackageVersionRelationshipsDeltasDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

