/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsReportRequestCreateRequestDataRelationshipsApp } from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';
import {
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON,
} from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';

/**
 * 
 * @export
 * @interface AnalyticsReportRequestCreateRequestDataRelationships
 */
export interface AnalyticsReportRequestCreateRequestDataRelationships {
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestDataRelationshipsApp}
     * @memberof AnalyticsReportRequestCreateRequestDataRelationships
     */
    app: AnalyticsReportRequestCreateRequestDataRelationshipsApp;
}

/**
 * Check if a given object implements the AnalyticsReportRequestCreateRequestDataRelationships interface.
 */
export function instanceOfAnalyticsReportRequestCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;

    return isInstance;
}

export function AnalyticsReportRequestCreateRequestDataRelationshipsFromJSON(json: any): AnalyticsReportRequestCreateRequestDataRelationships {
    return AnalyticsReportRequestCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function AnalyticsReportRequestCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsReportRequestCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON(json['app']),
    };
}

export function AnalyticsReportRequestCreateRequestDataRelationshipsToJSON(value?: AnalyticsReportRequestCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON(value.app),
    };
}

