/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionPackageVersionRelationshipsVariantsLinks } from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import {
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSONTyped,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON,
} from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import type { AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData } from './AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData';
import {
    AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceDataFromJSON,
    AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceDataFromJSONTyped,
    AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceDataToJSON,
} from './AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface AppClipRelationshipsAppClipDefaultExperiences
 */
export interface AppClipRelationshipsAppClipDefaultExperiences {
    /**
     * 
     * @type {AlternativeDistributionPackageVersionRelationshipsVariantsLinks}
     * @memberof AppClipRelationshipsAppClipDefaultExperiences
     */
    links?: AlternativeDistributionPackageVersionRelationshipsVariantsLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AppClipRelationshipsAppClipDefaultExperiences
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData>}
     * @memberof AppClipRelationshipsAppClipDefaultExperiences
     */
    data?: Array<AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData>;
}

/**
 * Check if a given object implements the AppClipRelationshipsAppClipDefaultExperiences interface.
 */
export function instanceOfAppClipRelationshipsAppClipDefaultExperiences(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppClipRelationshipsAppClipDefaultExperiencesFromJSON(json: any): AppClipRelationshipsAppClipDefaultExperiences {
    return AppClipRelationshipsAppClipDefaultExperiencesFromJSONTyped(json, false);
}

export function AppClipRelationshipsAppClipDefaultExperiencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipRelationshipsAppClipDefaultExperiences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceDataFromJSON)),
    };
}

export function AppClipRelationshipsAppClipDefaultExperiencesToJSON(value?: AppClipRelationshipsAppClipDefaultExperiences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceDataToJSON)),
    };
}

