/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppClipAdvancedExperienceAttributesPlacePhoneNumber
 */
export interface AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    type?: AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppClipAdvancedExperienceAttributesPlacePhoneNumber
     */
    intent?: string;
}


/**
 * @export
 */
export const AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum = {
    Fax: 'FAX',
    Landline: 'LANDLINE',
    Mobile: 'MOBILE',
    Tollfree: 'TOLLFREE'
} as const;
export type AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum = typeof AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum[keyof typeof AppClipAdvancedExperienceAttributesPlacePhoneNumberTypeEnum];


/**
 * Check if a given object implements the AppClipAdvancedExperienceAttributesPlacePhoneNumber interface.
 */
export function instanceOfAppClipAdvancedExperienceAttributesPlacePhoneNumber(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSON(json: any): AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    return AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSONTyped(json, false);
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppClipAdvancedExperienceAttributesPlacePhoneNumber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'intent': !exists(json, 'intent') ? undefined : json['intent'],
    };
}

export function AppClipAdvancedExperienceAttributesPlacePhoneNumberToJSON(value?: AppClipAdvancedExperienceAttributesPlacePhoneNumber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'type': value.type,
        'intent': value.intent,
    };
}

