/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionPackageVersionRelationshipsVariantsLinks } from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import {
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSONTyped,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON,
} from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import type { AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionData } from './AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionData';
import {
    AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionDataFromJSON,
    AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionDataFromJSONTyped,
    AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionDataToJSON,
} from './AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionData';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface AppCustomProductPageRelationshipsAppCustomProductPageVersions
 */
export interface AppCustomProductPageRelationshipsAppCustomProductPageVersions {
    /**
     * 
     * @type {AlternativeDistributionPackageVersionRelationshipsVariantsLinks}
     * @memberof AppCustomProductPageRelationshipsAppCustomProductPageVersions
     */
    links?: AlternativeDistributionPackageVersionRelationshipsVariantsLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AppCustomProductPageRelationshipsAppCustomProductPageVersions
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionData>}
     * @memberof AppCustomProductPageRelationshipsAppCustomProductPageVersions
     */
    data?: Array<AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionData>;
}

/**
 * Check if a given object implements the AppCustomProductPageRelationshipsAppCustomProductPageVersions interface.
 */
export function instanceOfAppCustomProductPageRelationshipsAppCustomProductPageVersions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppCustomProductPageRelationshipsAppCustomProductPageVersionsFromJSON(json: any): AppCustomProductPageRelationshipsAppCustomProductPageVersions {
    return AppCustomProductPageRelationshipsAppCustomProductPageVersionsFromJSONTyped(json, false);
}

export function AppCustomProductPageRelationshipsAppCustomProductPageVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppCustomProductPageRelationshipsAppCustomProductPageVersions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionDataFromJSON)),
    };
}

export function AppCustomProductPageRelationshipsAppCustomProductPageVersionsToJSON(value?: AppCustomProductPageRelationshipsAppCustomProductPageVersions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppCustomProductPageLocalizationRelationshipsAppCustomProductPageVersionDataToJSON)),
    };
}

