/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppEventAssetType } from './AppEventAssetType';
import {
    AppEventAssetTypeFromJSON,
    AppEventAssetTypeFromJSONTyped,
    AppEventAssetTypeToJSON,
} from './AppEventAssetType';

/**
 * 
 * @export
 * @interface AppEventScreenshotCreateRequestDataAttributes
 */
export interface AppEventScreenshotCreateRequestDataAttributes {
    /**
     * 
     * @type {number}
     * @memberof AppEventScreenshotCreateRequestDataAttributes
     */
    fileSize: number;
    /**
     * 
     * @type {string}
     * @memberof AppEventScreenshotCreateRequestDataAttributes
     */
    fileName: string;
    /**
     * 
     * @type {AppEventAssetType}
     * @memberof AppEventScreenshotCreateRequestDataAttributes
     */
    appEventAssetType: AppEventAssetType;
}

/**
 * Check if a given object implements the AppEventScreenshotCreateRequestDataAttributes interface.
 */
export function instanceOfAppEventScreenshotCreateRequestDataAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fileSize" in value;
    isInstance = isInstance && "fileName" in value;
    isInstance = isInstance && "appEventAssetType" in value;

    return isInstance;
}

export function AppEventScreenshotCreateRequestDataAttributesFromJSON(json: any): AppEventScreenshotCreateRequestDataAttributes {
    return AppEventScreenshotCreateRequestDataAttributesFromJSONTyped(json, false);
}

export function AppEventScreenshotCreateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEventScreenshotCreateRequestDataAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fileSize': json['fileSize'],
        'fileName': json['fileName'],
        'appEventAssetType': AppEventAssetTypeFromJSON(json['appEventAssetType']),
    };
}

export function AppEventScreenshotCreateRequestDataAttributesToJSON(value?: AppEventScreenshotCreateRequestDataAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fileSize': value.fileSize,
        'fileName': value.fileName,
        'appEventAssetType': AppEventAssetTypeToJSON(value.appEventAssetType),
    };
}

