/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints } from './AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints';
import {
    AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsFromJSON,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsFromJSONTyped,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsToJSON,
} from './AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints';
import type { AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions } from './AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions';
import {
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsFromJSON,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsFromJSONTyped,
    AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsToJSON,
} from './AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions';

/**
 * 
 * @export
 * @interface AppsBetaTesterUsagesV1MetricResponseDataInner
 */
export interface AppsBetaTesterUsagesV1MetricResponseDataInner {
    /**
     * 
     * @type {AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints}
     * @memberof AppsBetaTesterUsagesV1MetricResponseDataInner
     */
    dataPoints?: AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints;
    /**
     * 
     * @type {AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions}
     * @memberof AppsBetaTesterUsagesV1MetricResponseDataInner
     */
    dimensions?: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions;
}

/**
 * Check if a given object implements the AppsBetaTesterUsagesV1MetricResponseDataInner interface.
 */
export function instanceOfAppsBetaTesterUsagesV1MetricResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerFromJSON(json: any): AppsBetaTesterUsagesV1MetricResponseDataInner {
    return AppsBetaTesterUsagesV1MetricResponseDataInnerFromJSONTyped(json, false);
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppsBetaTesterUsagesV1MetricResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataPoints': !exists(json, 'dataPoints') ? undefined : AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsFromJSON(json['dataPoints']),
        'dimensions': !exists(json, 'dimensions') ? undefined : AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsFromJSON(json['dimensions']),
    };
}

export function AppsBetaTesterUsagesV1MetricResponseDataInnerToJSON(value?: AppsBetaTesterUsagesV1MetricResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataPoints': AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsToJSON(value.dataPoints),
        'dimensions': AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsToJSON(value.dimensions),
    };
}

