/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppUpdateRequestData } from './AppUpdateRequestData';
import {
    AppUpdateRequestDataFromJSON,
    AppUpdateRequestDataFromJSONTyped,
    AppUpdateRequestDataToJSON,
} from './AppUpdateRequestData';

/**
 * 
 * @export
 * @interface AppUpdateRequest
 */
export interface AppUpdateRequest {
    /**
     * 
     * @type {AppUpdateRequestData}
     * @memberof AppUpdateRequest
     */
    data: AppUpdateRequestData;
}

/**
 * Check if a given object implements the AppUpdateRequest interface.
 */
export function instanceOfAppUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function AppUpdateRequestFromJSON(json: any): AppUpdateRequest {
    return AppUpdateRequestFromJSONTyped(json, false);
}

export function AppUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AppUpdateRequestDataFromJSON(json['data']),
    };
}

export function AppUpdateRequestToJSON(value?: AppUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppUpdateRequestDataToJSON(value.data),
    };
}

