/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppUpdateRequestDataAttributes } from './AppUpdateRequestDataAttributes';
import {
    AppUpdateRequestDataAttributesFromJSON,
    AppUpdateRequestDataAttributesFromJSONTyped,
    AppUpdateRequestDataAttributesToJSON,
} from './AppUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface AppUpdateRequestData
 */
export interface AppUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppUpdateRequestData
     */
    type: AppUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {AppUpdateRequestDataAttributes}
     * @memberof AppUpdateRequestData
     */
    attributes?: AppUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const AppUpdateRequestDataTypeEnum = {
    Apps: 'apps'
} as const;
export type AppUpdateRequestDataTypeEnum = typeof AppUpdateRequestDataTypeEnum[keyof typeof AppUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppUpdateRequestData interface.
 */
export function instanceOfAppUpdateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AppUpdateRequestDataFromJSON(json: any): AppUpdateRequestData {
    return AppUpdateRequestDataFromJSONTyped(json, false);
}

export function AppUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUpdateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : AppUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function AppUpdateRequestDataToJSON(value?: AppUpdateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': AppUpdateRequestDataAttributesToJSON(value.attributes),
    };
}

