/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData
 */
export interface BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData {
    /**
     * 
     * @type {string}
     * @memberof BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData
     */
    type: BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData
     */
    id: string;
}


/**
 * @export
 */
export const BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataTypeEnum = {
    BetaAppClipInvocations: 'betaAppClipInvocations'
} as const;
export type BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataTypeEnum = typeof BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataTypeEnum[keyof typeof BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataTypeEnum];


/**
 * Check if a given object implements the BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData interface.
 */
export function instanceOfBetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataFromJSON(json: any): BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData {
    return BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataFromJSONTyped(json, false);
}

export function BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationDataToJSON(value?: BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

