/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsReportRequestCreateRequestDataRelationshipsApp } from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';
import {
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON,
} from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';
import type { BetaGroupCreateRequestDataRelationshipsBetaTesters } from './BetaGroupCreateRequestDataRelationshipsBetaTesters';
import {
    BetaGroupCreateRequestDataRelationshipsBetaTestersFromJSON,
    BetaGroupCreateRequestDataRelationshipsBetaTestersFromJSONTyped,
    BetaGroupCreateRequestDataRelationshipsBetaTestersToJSON,
} from './BetaGroupCreateRequestDataRelationshipsBetaTesters';
import type { BetaGroupCreateRequestDataRelationshipsBuilds } from './BetaGroupCreateRequestDataRelationshipsBuilds';
import {
    BetaGroupCreateRequestDataRelationshipsBuildsFromJSON,
    BetaGroupCreateRequestDataRelationshipsBuildsFromJSONTyped,
    BetaGroupCreateRequestDataRelationshipsBuildsToJSON,
} from './BetaGroupCreateRequestDataRelationshipsBuilds';

/**
 * 
 * @export
 * @interface BetaGroupCreateRequestDataRelationships
 */
export interface BetaGroupCreateRequestDataRelationships {
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestDataRelationshipsApp}
     * @memberof BetaGroupCreateRequestDataRelationships
     */
    app: AnalyticsReportRequestCreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {BetaGroupCreateRequestDataRelationshipsBuilds}
     * @memberof BetaGroupCreateRequestDataRelationships
     */
    builds?: BetaGroupCreateRequestDataRelationshipsBuilds;
    /**
     * 
     * @type {BetaGroupCreateRequestDataRelationshipsBetaTesters}
     * @memberof BetaGroupCreateRequestDataRelationships
     */
    betaTesters?: BetaGroupCreateRequestDataRelationshipsBetaTesters;
}

/**
 * Check if a given object implements the BetaGroupCreateRequestDataRelationships interface.
 */
export function instanceOfBetaGroupCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;

    return isInstance;
}

export function BetaGroupCreateRequestDataRelationshipsFromJSON(json: any): BetaGroupCreateRequestDataRelationships {
    return BetaGroupCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function BetaGroupCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaGroupCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON(json['app']),
        'builds': !exists(json, 'builds') ? undefined : BetaGroupCreateRequestDataRelationshipsBuildsFromJSON(json['builds']),
        'betaTesters': !exists(json, 'betaTesters') ? undefined : BetaGroupCreateRequestDataRelationshipsBetaTestersFromJSON(json['betaTesters']),
    };
}

export function BetaGroupCreateRequestDataRelationshipsToJSON(value?: BetaGroupCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON(value.app),
        'builds': BetaGroupCreateRequestDataRelationshipsBuildsToJSON(value.builds),
        'betaTesters': BetaGroupCreateRequestDataRelationshipsBetaTestersToJSON(value.betaTesters),
    };
}

