/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppEncryptionDeclarationRelationshipsBuildsDataInner } from './AppEncryptionDeclarationRelationshipsBuildsDataInner';
import {
    AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSON,
    AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSONTyped,
    AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSON,
} from './AppEncryptionDeclarationRelationshipsBuildsDataInner';

/**
 * 
 * @export
 * @interface BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild
 */
export interface BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
    /**
     * 
     * @type {AppEncryptionDeclarationRelationshipsBuildsDataInner}
     * @memberof BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild
     */
    data: AppEncryptionDeclarationRelationshipsBuildsDataInner;
}

/**
 * Check if a given object implements the BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild interface.
 */
export function instanceOfBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function BetaAppReviewSubmissionCreateRequestDataRelationshipsBuildFromJSON(json: any): BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
    return BetaAppReviewSubmissionCreateRequestDataRelationshipsBuildFromJSONTyped(json, false);
}

export function BetaAppReviewSubmissionCreateRequestDataRelationshipsBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AppEncryptionDeclarationRelationshipsBuildsDataInnerFromJSON(json['data']),
    };
}

export function BetaAppReviewSubmissionCreateRequestDataRelationshipsBuildToJSON(value?: BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppEncryptionDeclarationRelationshipsBuildsDataInnerToJSON(value.data),
    };
}

