/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Build,
    instanceOfBuild,
    BuildFromJSON,
    BuildFromJSONTyped,
    BuildToJSON,
} from './Build';
import {
    CiProduct,
    instanceOfCiProduct,
    CiProductFromJSON,
    CiProductFromJSONTyped,
    CiProductToJSON,
} from './CiProduct';
import {
    CiWorkflow,
    instanceOfCiWorkflow,
    CiWorkflowFromJSON,
    CiWorkflowFromJSONTyped,
    CiWorkflowToJSON,
} from './CiWorkflow';
import {
    ScmGitReference,
    instanceOfScmGitReference,
    ScmGitReferenceFromJSON,
    ScmGitReferenceFromJSONTyped,
    ScmGitReferenceToJSON,
} from './ScmGitReference';
import {
    ScmPullRequest,
    instanceOfScmPullRequest,
    ScmPullRequestFromJSON,
    ScmPullRequestFromJSONTyped,
    ScmPullRequestToJSON,
} from './ScmPullRequest';

/**
 * @type CiBuildRunsResponseIncludedInner
 * 
 * @export
 */
export type CiBuildRunsResponseIncludedInner = Build | CiProduct | CiWorkflow | ScmGitReference | ScmPullRequest;

export function CiBuildRunsResponseIncludedInnerFromJSON(json: any): CiBuildRunsResponseIncludedInner {
    return CiBuildRunsResponseIncludedInnerFromJSONTyped(json, false);
}

export function CiBuildRunsResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildRunsResponseIncludedInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BuildFromJSONTyped(json, true), ...CiProductFromJSONTyped(json, true), ...CiWorkflowFromJSONTyped(json, true), ...ScmGitReferenceFromJSONTyped(json, true), ...ScmPullRequestFromJSONTyped(json, true) };
}

export function CiBuildRunsResponseIncludedInnerToJSON(value?: CiBuildRunsResponseIncludedInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBuild(value)) {
        return BuildToJSON(value as Build);
    }
    if (instanceOfCiProduct(value)) {
        return CiProductToJSON(value as CiProduct);
    }
    if (instanceOfCiWorkflow(value)) {
        return CiWorkflowToJSON(value as CiWorkflow);
    }
    if (instanceOfScmGitReference(value)) {
        return ScmGitReferenceToJSON(value as ScmGitReference);
    }
    if (instanceOfScmPullRequest(value)) {
        return ScmPullRequestToJSON(value as ScmPullRequest);
    }

    return {};
}

