/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CiBuildRun } from './CiBuildRun';
import {
    CiBuildRunFromJSON,
    CiBuildRunFromJSONTyped,
    CiBuildRunToJSON,
} from './CiBuildRun';
import type { CiBuildRunsResponseIncludedInner } from './CiBuildRunsResponseIncludedInner';
import {
    CiBuildRunsResponseIncludedInnerFromJSON,
    CiBuildRunsResponseIncludedInnerFromJSONTyped,
    CiBuildRunsResponseIncludedInnerToJSON,
} from './CiBuildRunsResponseIncludedInner';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';

/**
 * 
 * @export
 * @interface CiBuildRunResponse
 */
export interface CiBuildRunResponse {
    /**
     * 
     * @type {CiBuildRun}
     * @memberof CiBuildRunResponse
     */
    data: CiBuildRun;
    /**
     * 
     * @type {Array<CiBuildRunsResponseIncludedInner>}
     * @memberof CiBuildRunResponse
     */
    included?: Array<CiBuildRunsResponseIncludedInner>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof CiBuildRunResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the CiBuildRunResponse interface.
 */
export function instanceOfCiBuildRunResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function CiBuildRunResponseFromJSON(json: any): CiBuildRunResponse {
    return CiBuildRunResponseFromJSONTyped(json, false);
}

export function CiBuildRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildRunResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CiBuildRunFromJSON(json['data']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(CiBuildRunsResponseIncludedInnerFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function CiBuildRunResponseToJSON(value?: CiBuildRunResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CiBuildRunToJSON(value.data),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(CiBuildRunsResponseIncludedInnerToJSON)),
        'links': DocumentLinksToJSON(value.links),
    };
}

