/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInsight } from './DiagnosticInsight';
import {
    DiagnosticInsightFromJSON,
    DiagnosticInsightFromJSONTyped,
    DiagnosticInsightToJSON,
} from './DiagnosticInsight';

/**
 * 
 * @export
 * @interface DiagnosticSignatureAttributes
 */
export interface DiagnosticSignatureAttributes {
    /**
     * 
     * @type {string}
     * @memberof DiagnosticSignatureAttributes
     */
    diagnosticType?: DiagnosticSignatureAttributesDiagnosticTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DiagnosticSignatureAttributes
     */
    signature?: string;
    /**
     * 
     * @type {number}
     * @memberof DiagnosticSignatureAttributes
     */
    weight?: number;
    /**
     * 
     * @type {DiagnosticInsight}
     * @memberof DiagnosticSignatureAttributes
     */
    insight?: DiagnosticInsight;
}


/**
 * @export
 */
export const DiagnosticSignatureAttributesDiagnosticTypeEnum = {
    DiskWrites: 'DISK_WRITES',
    Hangs: 'HANGS',
    Launches: 'LAUNCHES'
} as const;
export type DiagnosticSignatureAttributesDiagnosticTypeEnum = typeof DiagnosticSignatureAttributesDiagnosticTypeEnum[keyof typeof DiagnosticSignatureAttributesDiagnosticTypeEnum];


/**
 * Check if a given object implements the DiagnosticSignatureAttributes interface.
 */
export function instanceOfDiagnosticSignatureAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DiagnosticSignatureAttributesFromJSON(json: any): DiagnosticSignatureAttributes {
    return DiagnosticSignatureAttributesFromJSONTyped(json, false);
}

export function DiagnosticSignatureAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticSignatureAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'diagnosticType': !exists(json, 'diagnosticType') ? undefined : json['diagnosticType'],
        'signature': !exists(json, 'signature') ? undefined : json['signature'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'insight': !exists(json, 'insight') ? undefined : DiagnosticInsightFromJSON(json['insight']),
    };
}

export function DiagnosticSignatureAttributesToJSON(value?: DiagnosticSignatureAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'diagnosticType': value.diagnosticType,
        'signature': value.signature,
        'weight': value.weight,
        'insight': DiagnosticInsightToJSON(value.insight),
    };
}

