/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';
import type { EndAppAvailabilityPreOrder } from './EndAppAvailabilityPreOrder';
import {
    EndAppAvailabilityPreOrderFromJSON,
    EndAppAvailabilityPreOrderFromJSONTyped,
    EndAppAvailabilityPreOrderToJSON,
} from './EndAppAvailabilityPreOrder';

/**
 * 
 * @export
 * @interface EndAppAvailabilityPreOrderResponse
 */
export interface EndAppAvailabilityPreOrderResponse {
    /**
     * 
     * @type {EndAppAvailabilityPreOrder}
     * @memberof EndAppAvailabilityPreOrderResponse
     */
    data: EndAppAvailabilityPreOrder;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof EndAppAvailabilityPreOrderResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the EndAppAvailabilityPreOrderResponse interface.
 */
export function instanceOfEndAppAvailabilityPreOrderResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function EndAppAvailabilityPreOrderResponseFromJSON(json: any): EndAppAvailabilityPreOrderResponse {
    return EndAppAvailabilityPreOrderResponseFromJSONTyped(json, false);
}

export function EndAppAvailabilityPreOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndAppAvailabilityPreOrderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': EndAppAvailabilityPreOrderFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function EndAppAvailabilityPreOrderResponseToJSON(value?: EndAppAvailabilityPreOrderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': EndAppAvailabilityPreOrderToJSON(value.data),
        'links': DocumentLinksToJSON(value.links),
    };
}

