/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet } from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet';
import {
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSON,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSONTyped,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetToJSON,
} from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet';
import type { GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage } from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage';
import {
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSON,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSONTyped,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSON,
} from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetLocalizationRelationships
 */
export interface GameCenterLeaderboardSetLocalizationRelationships {
    /**
     * 
     * @type {GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet}
     * @memberof GameCenterLeaderboardSetLocalizationRelationships
     */
    gameCenterLeaderboardSet?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet;
    /**
     * 
     * @type {GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage}
     * @memberof GameCenterLeaderboardSetLocalizationRelationships
     */
    gameCenterLeaderboardSetImage?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetLocalizationRelationships interface.
 */
export function instanceOfGameCenterLeaderboardSetLocalizationRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterLeaderboardSetLocalizationRelationshipsFromJSON(json: any): GameCenterLeaderboardSetLocalizationRelationships {
    return GameCenterLeaderboardSetLocalizationRelationshipsFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetLocalizationRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetLocalizationRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameCenterLeaderboardSet': !exists(json, 'gameCenterLeaderboardSet') ? undefined : GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetFromJSON(json['gameCenterLeaderboardSet']),
        'gameCenterLeaderboardSetImage': !exists(json, 'gameCenterLeaderboardSetImage') ? undefined : GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSON(json['gameCenterLeaderboardSetImage']),
    };
}

export function GameCenterLeaderboardSetLocalizationRelationshipsToJSON(value?: GameCenterLeaderboardSetLocalizationRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameCenterLeaderboardSet': GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetToJSON(value.gameCenterLeaderboardSet),
        'gameCenterLeaderboardSetImage': GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSON(value.gameCenterLeaderboardSetImage),
    };
}

