/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';
import type { GameCenterAchievement } from './GameCenterAchievement';
import {
    GameCenterAchievementFromJSON,
    GameCenterAchievementFromJSONTyped,
    GameCenterAchievementToJSON,
} from './GameCenterAchievement';
import type { GameCenterAchievementsResponseIncludedInner } from './GameCenterAchievementsResponseIncludedInner';
import {
    GameCenterAchievementsResponseIncludedInnerFromJSON,
    GameCenterAchievementsResponseIncludedInnerFromJSONTyped,
    GameCenterAchievementsResponseIncludedInnerToJSON,
} from './GameCenterAchievementsResponseIncludedInner';

/**
 * 
 * @export
 * @interface GameCenterAchievementResponse
 */
export interface GameCenterAchievementResponse {
    /**
     * 
     * @type {GameCenterAchievement}
     * @memberof GameCenterAchievementResponse
     */
    data: GameCenterAchievement;
    /**
     * 
     * @type {Array<GameCenterAchievementsResponseIncludedInner>}
     * @memberof GameCenterAchievementResponse
     */
    included?: Array<GameCenterAchievementsResponseIncludedInner>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof GameCenterAchievementResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the GameCenterAchievementResponse interface.
 */
export function instanceOfGameCenterAchievementResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GameCenterAchievementResponseFromJSON(json: any): GameCenterAchievementResponse {
    return GameCenterAchievementResponseFromJSONTyped(json, false);
}

export function GameCenterAchievementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GameCenterAchievementFromJSON(json['data']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(GameCenterAchievementsResponseIncludedInnerFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function GameCenterAchievementResponseToJSON(value?: GameCenterAchievementResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GameCenterAchievementToJSON(value.data),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(GameCenterAchievementsResponseIncludedInnerToJSON)),
        'links': DocumentLinksToJSON(value.links),
    };
}

