/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterMatchmakingTeamAssignment } from './GameCenterMatchmakingTeamAssignment';
import {
    GameCenterMatchmakingTeamAssignmentFromJSON,
    GameCenterMatchmakingTeamAssignmentFromJSONTyped,
    GameCenterMatchmakingTeamAssignmentToJSON,
} from './GameCenterMatchmakingTeamAssignment';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner
 */
export interface GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner {
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner
     */
    requestName?: string;
    /**
     * 
     * @type {Array<GameCenterMatchmakingTeamAssignment>}
     * @memberof GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner
     */
    teamAssignments?: Array<GameCenterMatchmakingTeamAssignment>;
}

/**
 * Check if a given object implements the GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner interface.
 */
export function instanceOfGameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInnerFromJSON(json: any): GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner {
    return GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInnerFromJSONTyped(json, false);
}

export function GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestName': !exists(json, 'requestName') ? undefined : json['requestName'],
        'teamAssignments': !exists(json, 'teamAssignments') ? undefined : ((json['teamAssignments'] as Array<any>).map(GameCenterMatchmakingTeamAssignmentFromJSON)),
    };
}

export function GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInnerToJSON(value?: GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestName': value.requestName,
        'teamAssignments': value.teamAssignments === undefined ? undefined : ((value.teamAssignments as Array<any>).map(GameCenterMatchmakingTeamAssignmentToJSON)),
    };
}

