/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement } from './GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement';
import {
    GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievementFromJSON,
    GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievementFromJSONTyped,
    GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievementToJSON,
} from './GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement';
import type { GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail } from './GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail';
import {
    GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetailFromJSON,
    GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetailFromJSONTyped,
    GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetailToJSON,
} from './GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail';

/**
 * 
 * @export
 * @interface GameCenterAchievementReleaseCreateRequestDataRelationships
 */
export interface GameCenterAchievementReleaseCreateRequestDataRelationships {
    /**
     * 
     * @type {GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail}
     * @memberof GameCenterAchievementReleaseCreateRequestDataRelationships
     */
    gameCenterDetail: GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail;
    /**
     * 
     * @type {GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement}
     * @memberof GameCenterAchievementReleaseCreateRequestDataRelationships
     */
    gameCenterAchievement: GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement;
}

/**
 * Check if a given object implements the GameCenterAchievementReleaseCreateRequestDataRelationships interface.
 */
export function instanceOfGameCenterAchievementReleaseCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gameCenterDetail" in value;
    isInstance = isInstance && "gameCenterAchievement" in value;

    return isInstance;
}

export function GameCenterAchievementReleaseCreateRequestDataRelationshipsFromJSON(json: any): GameCenterAchievementReleaseCreateRequestDataRelationships {
    return GameCenterAchievementReleaseCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function GameCenterAchievementReleaseCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementReleaseCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameCenterDetail': GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetailFromJSON(json['gameCenterDetail']),
        'gameCenterAchievement': GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievementFromJSON(json['gameCenterAchievement']),
    };
}

export function GameCenterAchievementReleaseCreateRequestDataRelationshipsToJSON(value?: GameCenterAchievementReleaseCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameCenterDetail': GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetailToJSON(value.gameCenterDetail),
        'gameCenterAchievement': GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievementToJSON(value.gameCenterAchievement),
    };
}

