/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardGroupLeaderboardLinkageResponse
 */
export interface GameCenterLeaderboardGroupLeaderboardLinkageResponse {
    /**
     * 
     * @type {GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner}
     * @memberof GameCenterLeaderboardGroupLeaderboardLinkageResponse
     */
    data: GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof GameCenterLeaderboardGroupLeaderboardLinkageResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the GameCenterLeaderboardGroupLeaderboardLinkageResponse interface.
 */
export function instanceOfGameCenterLeaderboardGroupLeaderboardLinkageResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GameCenterLeaderboardGroupLeaderboardLinkageResponseFromJSON(json: any): GameCenterLeaderboardGroupLeaderboardLinkageResponse {
    return GameCenterLeaderboardGroupLeaderboardLinkageResponseFromJSONTyped(json, false);
}

export function GameCenterLeaderboardGroupLeaderboardLinkageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardGroupLeaderboardLinkageResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON(json['data']),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function GameCenterLeaderboardGroupLeaderboardLinkageResponseToJSON(value?: GameCenterLeaderboardGroupLeaderboardLinkageResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON(value.data),
        'links': DocumentLinksToJSON(value.links),
    };
}

