/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentLinks } from './DocumentLinks';
import {
    DocumentLinksFromJSON,
    DocumentLinksFromJSONTyped,
    DocumentLinksToJSON,
} from './DocumentLinks';
import type { GameCenterLeaderboardLocalization } from './GameCenterLeaderboardLocalization';
import {
    GameCenterLeaderboardLocalizationFromJSON,
    GameCenterLeaderboardLocalizationFromJSONTyped,
    GameCenterLeaderboardLocalizationToJSON,
} from './GameCenterLeaderboardLocalization';
import type { GameCenterLeaderboardLocalizationsResponseIncludedInner } from './GameCenterLeaderboardLocalizationsResponseIncludedInner';
import {
    GameCenterLeaderboardLocalizationsResponseIncludedInnerFromJSON,
    GameCenterLeaderboardLocalizationsResponseIncludedInnerFromJSONTyped,
    GameCenterLeaderboardLocalizationsResponseIncludedInnerToJSON,
} from './GameCenterLeaderboardLocalizationsResponseIncludedInner';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardLocalizationResponse
 */
export interface GameCenterLeaderboardLocalizationResponse {
    /**
     * 
     * @type {GameCenterLeaderboardLocalization}
     * @memberof GameCenterLeaderboardLocalizationResponse
     */
    data: GameCenterLeaderboardLocalization;
    /**
     * 
     * @type {Array<GameCenterLeaderboardLocalizationsResponseIncludedInner>}
     * @memberof GameCenterLeaderboardLocalizationResponse
     */
    included?: Array<GameCenterLeaderboardLocalizationsResponseIncludedInner>;
    /**
     * 
     * @type {DocumentLinks}
     * @memberof GameCenterLeaderboardLocalizationResponse
     */
    links: DocumentLinks;
}

/**
 * Check if a given object implements the GameCenterLeaderboardLocalizationResponse interface.
 */
export function instanceOfGameCenterLeaderboardLocalizationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GameCenterLeaderboardLocalizationResponseFromJSON(json: any): GameCenterLeaderboardLocalizationResponse {
    return GameCenterLeaderboardLocalizationResponseFromJSONTyped(json, false);
}

export function GameCenterLeaderboardLocalizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardLocalizationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GameCenterLeaderboardLocalizationFromJSON(json['data']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(GameCenterLeaderboardLocalizationsResponseIncludedInnerFromJSON)),
        'links': DocumentLinksFromJSON(json['links']),
    };
}

export function GameCenterLeaderboardLocalizationResponseToJSON(value?: GameCenterLeaderboardLocalizationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GameCenterLeaderboardLocalizationToJSON(value.data),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(GameCenterLeaderboardLocalizationsResponseIncludedInnerToJSON)),
        'links': DocumentLinksToJSON(value.links),
    };
}

