/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterDetailAttributes } from './GameCenterDetailAttributes';
import {
    GameCenterDetailAttributesFromJSON,
    GameCenterDetailAttributesFromJSONTyped,
    GameCenterDetailAttributesToJSON,
} from './GameCenterDetailAttributes';
import type { GameCenterDetailRelationships } from './GameCenterDetailRelationships';
import {
    GameCenterDetailRelationshipsFromJSON,
    GameCenterDetailRelationshipsFromJSONTyped,
    GameCenterDetailRelationshipsToJSON,
} from './GameCenterDetailRelationships';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface GameCenterDetail
 */
export interface GameCenterDetail {
    /**
     * 
     * @type {string}
     * @memberof GameCenterDetail
     */
    type: GameCenterDetailTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameCenterDetail
     */
    id: string;
    /**
     * 
     * @type {GameCenterDetailAttributes}
     * @memberof GameCenterDetail
     */
    attributes?: GameCenterDetailAttributes;
    /**
     * 
     * @type {GameCenterDetailRelationships}
     * @memberof GameCenterDetail
     */
    relationships?: GameCenterDetailRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof GameCenterDetail
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const GameCenterDetailTypeEnum = {
    GameCenterDetails: 'gameCenterDetails'
} as const;
export type GameCenterDetailTypeEnum = typeof GameCenterDetailTypeEnum[keyof typeof GameCenterDetailTypeEnum];


/**
 * Check if a given object implements the GameCenterDetail interface.
 */
export function instanceOfGameCenterDetail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GameCenterDetailFromJSON(json: any): GameCenterDetail {
    return GameCenterDetailFromJSONTyped(json, false);
}

export function GameCenterDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : GameCenterDetailAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GameCenterDetailRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function GameCenterDetailToJSON(value?: GameCenterDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GameCenterDetailAttributesToJSON(value.attributes),
        'relationships': GameCenterDetailRelationshipsToJSON(value.relationships),
        'links': ResourceLinksToJSON(value.links),
    };
}

