/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints } from './GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints';
import {
    GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsFromJSON,
    GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsFromJSONTyped,
    GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsToJSON,
} from './GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
 */
export interface GameCenterMatchmakingQueueSizesV1MetricResponseDataInner {
    /**
     * 
     * @type {GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints}
     * @memberof GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
     */
    dataPoints?: GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPoints;
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingQueueSizesV1MetricResponseDataInner
     */
    granularity?: GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerGranularityEnum;
}


/**
 * @export
 */
export const GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerGranularityEnum = {
    P1D: 'P1D',
    Pt1H: 'PT1H',
    Pt15M: 'PT15M'
} as const;
export type GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerGranularityEnum = typeof GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerGranularityEnum[keyof typeof GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerGranularityEnum];


/**
 * Check if a given object implements the GameCenterMatchmakingQueueSizesV1MetricResponseDataInner interface.
 */
export function instanceOfGameCenterMatchmakingQueueSizesV1MetricResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerFromJSON(json: any): GameCenterMatchmakingQueueSizesV1MetricResponseDataInner {
    return GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerFromJSONTyped(json, false);
}

export function GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingQueueSizesV1MetricResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataPoints': !exists(json, 'dataPoints') ? undefined : GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsFromJSON(json['dataPoints']),
        'granularity': !exists(json, 'granularity') ? undefined : json['granularity'],
    };
}

export function GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerToJSON(value?: GameCenterMatchmakingQueueSizesV1MetricResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataPoints': GameCenterMatchmakingQueueSizesV1MetricResponseDataInnerDataPointsToJSON(value.dataPoints),
        'granularity': value.granularity,
    };
}

