/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterAchievementReleaseCreateRequestData } from './GameCenterAchievementReleaseCreateRequestData';
import {
    GameCenterAchievementReleaseCreateRequestDataFromJSON,
    GameCenterAchievementReleaseCreateRequestDataFromJSONTyped,
    GameCenterAchievementReleaseCreateRequestDataToJSON,
} from './GameCenterAchievementReleaseCreateRequestData';

/**
 * 
 * @export
 * @interface GameCenterAchievementReleaseCreateRequest
 */
export interface GameCenterAchievementReleaseCreateRequest {
    /**
     * 
     * @type {GameCenterAchievementReleaseCreateRequestData}
     * @memberof GameCenterAchievementReleaseCreateRequest
     */
    data: GameCenterAchievementReleaseCreateRequestData;
}

/**
 * Check if a given object implements the GameCenterAchievementReleaseCreateRequest interface.
 */
export function instanceOfGameCenterAchievementReleaseCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GameCenterAchievementReleaseCreateRequestFromJSON(json: any): GameCenterAchievementReleaseCreateRequest {
    return GameCenterAchievementReleaseCreateRequestFromJSONTyped(json, false);
}

export function GameCenterAchievementReleaseCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementReleaseCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GameCenterAchievementReleaseCreateRequestDataFromJSON(json['data']),
    };
}

export function GameCenterAchievementReleaseCreateRequestToJSON(value?: GameCenterAchievementReleaseCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GameCenterAchievementReleaseCreateRequestDataToJSON(value.data),
    };
}

