/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionPackageVersionRelationshipsVariantsLinks } from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import {
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSONTyped,
    AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON,
} from './AlternativeDistributionPackageVersionRelationshipsVariantsLinks';
import type { InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData } from './InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData';
import {
    InAppPurchaseV2RelationshipsAppStoreReviewScreenshotDataFromJSON,
    InAppPurchaseV2RelationshipsAppStoreReviewScreenshotDataFromJSONTyped,
    InAppPurchaseV2RelationshipsAppStoreReviewScreenshotDataToJSON,
} from './InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData';

/**
 * 
 * @export
 * @interface InAppPurchaseV2RelationshipsAppStoreReviewScreenshot
 */
export interface InAppPurchaseV2RelationshipsAppStoreReviewScreenshot {
    /**
     * 
     * @type {AlternativeDistributionPackageVersionRelationshipsVariantsLinks}
     * @memberof InAppPurchaseV2RelationshipsAppStoreReviewScreenshot
     */
    links?: AlternativeDistributionPackageVersionRelationshipsVariantsLinks;
    /**
     * 
     * @type {InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData}
     * @memberof InAppPurchaseV2RelationshipsAppStoreReviewScreenshot
     */
    data?: InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData;
}

/**
 * Check if a given object implements the InAppPurchaseV2RelationshipsAppStoreReviewScreenshot interface.
 */
export function instanceOfInAppPurchaseV2RelationshipsAppStoreReviewScreenshot(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InAppPurchaseV2RelationshipsAppStoreReviewScreenshotFromJSON(json: any): InAppPurchaseV2RelationshipsAppStoreReviewScreenshot {
    return InAppPurchaseV2RelationshipsAppStoreReviewScreenshotFromJSONTyped(json, false);
}

export function InAppPurchaseV2RelationshipsAppStoreReviewScreenshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseV2RelationshipsAppStoreReviewScreenshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AlternativeDistributionPackageVersionRelationshipsVariantsLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : InAppPurchaseV2RelationshipsAppStoreReviewScreenshotDataFromJSON(json['data']),
    };
}

export function InAppPurchaseV2RelationshipsAppStoreReviewScreenshotToJSON(value?: InAppPurchaseV2RelationshipsAppStoreReviewScreenshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AlternativeDistributionPackageVersionRelationshipsVariantsLinksToJSON(value.links),
        'data': InAppPurchaseV2RelationshipsAppStoreReviewScreenshotDataToJSON(value.data),
    };
}

