/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReviewSubmissionItemUpdateRequestDataAttributes } from './ReviewSubmissionItemUpdateRequestDataAttributes';
import {
    ReviewSubmissionItemUpdateRequestDataAttributesFromJSON,
    ReviewSubmissionItemUpdateRequestDataAttributesFromJSONTyped,
    ReviewSubmissionItemUpdateRequestDataAttributesToJSON,
} from './ReviewSubmissionItemUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface ReviewSubmissionItemUpdateRequestData
 */
export interface ReviewSubmissionItemUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionItemUpdateRequestData
     */
    type: ReviewSubmissionItemUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionItemUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {ReviewSubmissionItemUpdateRequestDataAttributes}
     * @memberof ReviewSubmissionItemUpdateRequestData
     */
    attributes?: ReviewSubmissionItemUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const ReviewSubmissionItemUpdateRequestDataTypeEnum = {
    ReviewSubmissionItems: 'reviewSubmissionItems'
} as const;
export type ReviewSubmissionItemUpdateRequestDataTypeEnum = typeof ReviewSubmissionItemUpdateRequestDataTypeEnum[keyof typeof ReviewSubmissionItemUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the ReviewSubmissionItemUpdateRequestData interface.
 */
export function instanceOfReviewSubmissionItemUpdateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ReviewSubmissionItemUpdateRequestDataFromJSON(json: any): ReviewSubmissionItemUpdateRequestData {
    return ReviewSubmissionItemUpdateRequestDataFromJSONTyped(json, false);
}

export function ReviewSubmissionItemUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionItemUpdateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : ReviewSubmissionItemUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function ReviewSubmissionItemUpdateRequestDataToJSON(value?: ReviewSubmissionItemUpdateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': ReviewSubmissionItemUpdateRequestDataAttributesToJSON(value.attributes),
    };
}

