/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubscriptionLocalizationCreateRequestData } from './SubscriptionLocalizationCreateRequestData';
import {
    SubscriptionLocalizationCreateRequestDataFromJSON,
    SubscriptionLocalizationCreateRequestDataFromJSONTyped,
    SubscriptionLocalizationCreateRequestDataToJSON,
} from './SubscriptionLocalizationCreateRequestData';

/**
 * 
 * @export
 * @interface SubscriptionLocalizationCreateRequest
 */
export interface SubscriptionLocalizationCreateRequest {
    /**
     * 
     * @type {SubscriptionLocalizationCreateRequestData}
     * @memberof SubscriptionLocalizationCreateRequest
     */
    data: SubscriptionLocalizationCreateRequestData;
}

/**
 * Check if a given object implements the SubscriptionLocalizationCreateRequest interface.
 */
export function instanceOfSubscriptionLocalizationCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SubscriptionLocalizationCreateRequestFromJSON(json: any): SubscriptionLocalizationCreateRequest {
    return SubscriptionLocalizationCreateRequestFromJSONTyped(json, false);
}

export function SubscriptionLocalizationCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionLocalizationCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': SubscriptionLocalizationCreateRequestDataFromJSON(json['data']),
    };
}

export function SubscriptionLocalizationCreateRequestToJSON(value?: SubscriptionLocalizationCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SubscriptionLocalizationCreateRequestDataToJSON(value.data),
    };
}

