/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionPricePointInlineCreate
 */
export interface SubscriptionPricePointInlineCreate {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPricePointInlineCreate
     */
    type: SubscriptionPricePointInlineCreateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPricePointInlineCreate
     */
    id?: string;
}


/**
 * @export
 */
export const SubscriptionPricePointInlineCreateTypeEnum = {
    SubscriptionPricePoints: 'subscriptionPricePoints'
} as const;
export type SubscriptionPricePointInlineCreateTypeEnum = typeof SubscriptionPricePointInlineCreateTypeEnum[keyof typeof SubscriptionPricePointInlineCreateTypeEnum];


/**
 * Check if a given object implements the SubscriptionPricePointInlineCreate interface.
 */
export function instanceOfSubscriptionPricePointInlineCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function SubscriptionPricePointInlineCreateFromJSON(json: any): SubscriptionPricePointInlineCreate {
    return SubscriptionPricePointInlineCreateFromJSONTyped(json, false);
}

export function SubscriptionPricePointInlineCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPricePointInlineCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SubscriptionPricePointInlineCreateToJSON(value?: SubscriptionPricePointInlineCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

