/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionPromotionalOfferRelationshipsPricesDataInner
 */
export interface SubscriptionPromotionalOfferRelationshipsPricesDataInner {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPromotionalOfferRelationshipsPricesDataInner
     */
    type: SubscriptionPromotionalOfferRelationshipsPricesDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPromotionalOfferRelationshipsPricesDataInner
     */
    id: string;
}


/**
 * @export
 */
export const SubscriptionPromotionalOfferRelationshipsPricesDataInnerTypeEnum = {
    SubscriptionPromotionalOfferPrices: 'subscriptionPromotionalOfferPrices'
} as const;
export type SubscriptionPromotionalOfferRelationshipsPricesDataInnerTypeEnum = typeof SubscriptionPromotionalOfferRelationshipsPricesDataInnerTypeEnum[keyof typeof SubscriptionPromotionalOfferRelationshipsPricesDataInnerTypeEnum];


/**
 * Check if a given object implements the SubscriptionPromotionalOfferRelationshipsPricesDataInner interface.
 */
export function instanceOfSubscriptionPromotionalOfferRelationshipsPricesDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SubscriptionPromotionalOfferRelationshipsPricesDataInnerFromJSON(json: any): SubscriptionPromotionalOfferRelationshipsPricesDataInner {
    return SubscriptionPromotionalOfferRelationshipsPricesDataInnerFromJSONTyped(json, false);
}

export function SubscriptionPromotionalOfferRelationshipsPricesDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPromotionalOfferRelationshipsPricesDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function SubscriptionPromotionalOfferRelationshipsPricesDataInnerToJSON(value?: SubscriptionPromotionalOfferRelationshipsPricesDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

