/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointData } from './SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointData';
import {
    SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointDataFromJSON,
    SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointDataFromJSONTyped,
    SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointDataToJSON,
} from './SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointData';

/**
 * 
 * @export
 * @interface SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint
 */
export interface SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint {
    /**
     * 
     * @type {SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointData}
     * @memberof SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint
     */
    data?: SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointData;
}

/**
 * Check if a given object implements the SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint interface.
 */
export function instanceOfSubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSON(json: any): SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint {
    return SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointDataFromJSON(json['data']),
    };
}

export function SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePointToJSON(value?: SubscriptionIntroductoryOfferInlineCreateRelationshipsSubscriptionPricePoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePointDataToJSON(value.data),
    };
}

