/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  SandboxTestersClearPurchaseHistoryRequestV2CreateRequest,
  SandboxTestersClearPurchaseHistoryRequestV2Response,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    SandboxTestersClearPurchaseHistoryRequestV2CreateRequestFromJSON,
    SandboxTestersClearPurchaseHistoryRequestV2CreateRequestToJSON,
    SandboxTestersClearPurchaseHistoryRequestV2ResponseFromJSON,
    SandboxTestersClearPurchaseHistoryRequestV2ResponseToJSON,
} from '../models';

export interface SandboxTestersClearPurchaseHistoryRequestCreateInstanceRequest {
    sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: SandboxTestersClearPurchaseHistoryRequestV2CreateRequest;
}

/**
 * 
 */
export class SandboxTestersClearPurchaseHistoryRequestApi extends runtime.BaseAPI {

    /**
     */
    async sandboxTestersClearPurchaseHistoryRequestCreateInstanceRaw(requestParameters: SandboxTestersClearPurchaseHistoryRequestCreateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxTestersClearPurchaseHistoryRequestV2Response>> {
        if (requestParameters.sandboxTestersClearPurchaseHistoryRequestV2CreateRequest === null || requestParameters.sandboxTestersClearPurchaseHistoryRequestV2CreateRequest === undefined) {
            throw new runtime.RequiredError('sandboxTestersClearPurchaseHistoryRequestV2CreateRequest','Required parameter requestParameters.sandboxTestersClearPurchaseHistoryRequestV2CreateRequest was null or undefined when calling sandboxTestersClearPurchaseHistoryRequestCreateInstance.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itc-bearer-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/sandboxTestersClearPurchaseHistoryRequest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SandboxTestersClearPurchaseHistoryRequestV2CreateRequestToJSON(requestParameters.sandboxTestersClearPurchaseHistoryRequestV2CreateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxTestersClearPurchaseHistoryRequestV2ResponseFromJSON(jsonValue));
    }

    /**
     */
    async sandboxTestersClearPurchaseHistoryRequestCreateInstance(requestParameters: SandboxTestersClearPurchaseHistoryRequestCreateInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxTestersClearPurchaseHistoryRequestV2Response> {
        const response = await this.sandboxTestersClearPurchaseHistoryRequestCreateInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
